In [2]:
import pandas as pd
df=pd.read_csv("sale.csv")
df

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
0     O0001  27/10/23   East       C001      P008         7        653
1     O0002  25/01/23  North       C008      P010         6        690
2     O0003  29/11/24   West       C008      P006         7        433
3     O0004  21/03/24   West       C009      P008         4        984
4     O0005  22/01/23  South       C020      P002         2        850
..      ...       ...    ...        ...       ...       ...        ...
295   O0296  28/07/24  South       C018      P006         7        497
296   O0297  31/01/24  South       C012      P007         1        647
297   O0298  28/10/24  South       C011      P001         9        296
298   O0299  27/03/23   West       C002      P006         2        763
299   O0300  22/11/23   East       C017      P006         4        124

[300 rows x 7 columns]

In [3]:
#This show only thes selected columns (OrderId and Region)
df_two=df[["OrderID","Region"]]
df_two

    OrderID Region
0     O0001   East
1     O0002  North
2     O0003   West
3     O0004   West
4     O0005  South
..      ...    ...
295   O0296  South
296   O0297  South
297   O0298  South
298   O0299   West
299   O0300   East

[300 rows x 2 columns]

In [5]:
#This dispaly rows where the values are higher then average of unitprice
df_avg=df["UnitPrice"].mean()
df_above_avg=df[df["UnitPrice"]>df_avg]
df_above_avg

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
0     O0001  27/10/23   East       C001      P008         7        653
1     O0002  25/01/23  North       C008      P010         6        690
3     O0004  21/03/24   West       C009      P008         4        984
4     O0005  22/01/23  South       C020      P002         2        850
5     O0006  21/06/24   West       C018      P005         7        567
..      ...       ...    ...        ...       ...       ...        ...
285   O0286  25/12/23  South       C007      P001         3        563
293   O0294  15/01/23  North       C003      P003         3        622
294   O0295  09/06/24  South       C001      P008         5        884
296   O0297  31/01/24  South       C012      P007         1        647
298   O0299  27/03/23   West       C002      P006         2        763

[158 rows x 7 columns]

In [7]:
#This show the sort the dataset from highest to lowest values of Quantity
df_sort=df.sort_values(by="Quantity",ascending=False)
df_sort

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
244   O0245  26/12/23   East       C001      P008        10        622
214   O0215  25/12/23   East       C016      P006        10        825
128   O0129  19/03/24  South       C016      P009        10        212
278   O0279  25/04/24   East       C001      P001        10        867
256   O0257  24/09/23  North       C014      P002        10        193
..      ...       ...    ...        ...       ...       ...        ...
185   O0186  13/03/23   West       C014      P010         1        183
242   O0243  22/09/24   East       C005      P006         1        748
158   O0159  17/10/24  North       C007      P001         1        796
259   O0260  11/07/24   West       C005      P004         1        616
64    O0065  02/01/23   East       C019      P007         1        980

[300 rows x 7 columns]

In [20]:
#This show dataset with condition: quantity greater than 8 and unitprice greater than 800
df_filter=df[(df["Quantity"]>8) & (df["UnitPrice"]>800)]
df_filter

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
30    O0031  17/04/23  South       C016      P003         9        998
31    O0032  11/11/23   East       C013      P006        10        923
56    O0057  19/08/24   West       C007      P006         9        992
78    O0079  11/03/23  South       C011      P004         9        923
83    O0084  10/05/23  South       C006      P003         9        902
113   O0114  20/03/24  South       C001      P004         9        995
115   O0116  25/11/23   West       C006      P006        10        913
135   O0136  17/03/23   East       C005      P010        10        923
137   O0138  07/11/23   West       C018      P010         9        969
138   O0139  21/08/23  South       C010      P010         9        817
145   O0146  11/02/24  South       C004      P009         9        950
155   O0156  09/08/24  South       C003      P002        10        820
214   O0215  25/12/23   East       C016      P006        10        825
215   O0216  25/11/24   East       C011      P010         9        982
219   O0220  02/06/24   West       C004      P006        10        833
274   O0275  18/07/23   West       C016      P008        10        897
278   O0279  25/04/24   East       C001      P001        10        867