In [1]:
import pandas as pd
df=pd.read_csv("messy_sales_dataset.csv")
df.head()

,CustomerID,Name,Age,Gender,Country,Sales,OrderDate,Product,Quantity,Discount
0,CUST1000,MARY,30,male,NaN,NaN,March 3 2023,Tablet,NaN,NaN
1,CUST1001,Mary,NaN,male,NaN,100.5,NaN,phone,five,NaN
2,CUST1002,JOHN,35,female,INDIA,200.75,NaN,PHONE,NaN,5 percent
3,CUST1003,MARY,NaN,Male,NaN,200.75,2023-01-01,Tablet,2,5 percent
4,CUST1004,mary,unknown,NaN,INDIA,100.5,2023-01-01,Tablet,3,10%

In [2]:
df.isnull().sum()

CustomerID      0
Name            0
Age           226
Gender        247
Country       217
Sales         214
OrderDate     317
Product         0
Quantity      265
Discount      315
dtype: int64

In [ ]:
# This shows how many missing values exist in each column

In [4]:
df=df.dropna(subset=["Age"])

CustomerID      0
Name            0
Age             0
Gender        205
Country       176
Sales         170
OrderDate     254
Product         0
Quantity      225
Discount      260
dtype: int64

In [ ]:
# Drop rows where a key column is missing or null  because they cannot be reliably used in analysis.

In [13]:
df["Gender"]=df["Gender"].fillna("Unknown")
df["Gender"]

0          male
2        female
4       Unknown
5          Male
8          male
         ...
1194     female
1195     female
1196    Unknown
1197       male
1198       Male
Name: Gender, Length: 983, dtype: object

In [7]:
# Missing values were filled to avoid losing data

In [14]:
df=df.drop_duplicates()
df

,CustomerID,Name,Age,Gender,Country,Sales,OrderDate,Product,Quantity,Discount
0,CUST1000,MARY,30,male,NaN,NaN,March 3 2023,Tablet,NaN,NaN
2,CUST1002,JOHN,35,female,INDIA,200.75,NaN,PHONE,NaN,5 percent
4,CUST1004,mary,unknown,Unknown,INDIA,100.5,2023-01-01,Tablet,3,10%
5,CUST1005,MARY,40,Male,NaN,invalid,01/02/2023,phone,NaN,10%
8,CUST1008,mary,unknown,male,India,300$,March 3 2023,Tablet,1,0.2
...,...,...,...,...,...,...,...,...,...,...
1194,CUST2194,John,25,female,usa,100.5,2023-01-01,PHONE,1,0.2
1195,CUST2195,mary,40,female,INDIA,200.75,NaN,laptop,NaN,NaN
1196,CUST2196,alex,35,Unknown,usa,invalid,NaN,PHONE,1,0.2
1197,CUST2197,MARY,40,male,NaN,200.75,01/02/2023,phone,1,5 percent
1198,CUST2198,mary,30,Male,usa,200.75,NaN,laptop,3,0.2

In [9]:
## Duplicate rows were removed to prevent double counting and incorrect analysis.

In [11]:
df.dtypes

CustomerID    object
Name          object
Age           object
Gender        object
Country       object
Sales         object
OrderDate     object
Product       object
Quantity      object
Discount      object
dtype: object

In [19]:
df["Sales"]=pd.to_numeric(df["Sales"],errors="coerce")
df["OrderDate"]=pd.to_datetime(df["OrderDate"],errors="coerce")
df.dtypes

CustomerID            object
Name                  object
Age                   object
Gender                object
Country               object
Sales                float64
OrderDate     datetime64[ns]
Product               object
Quantity              object
Discount              object
dtype: object

In [20]:
# Data type was corrected to ensure proper calculations and analysis